/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 62
#define YY_END_OF_BUFFER 63
static yyconst short int yy_accept[348] =
    {   0,
        0,    0,   63,   61,   59,   59,   61,   61,   61,   61,
       61,   46,   47,   56,   61,   61,   13,   57,   61,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   43,   61,   45,    0,
        0,   18,    0,   48,    0,   13,   44,    0,    0,    0,
        0,   60,    0,   13,   19,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   49,    0,    0,    0,
        3,   15,   54,   53,   50,   52,   51,   55,   60,    0,

       14,    0,   13,   16,   16,    9,   16,   16,   16,   16,
       16,   16,   16,   12,   42,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   11,    0,    0,
       23,   16,   16,   16,   16,   16,   10,   16,   16,    4,
       16,   26,   22,   33,   16,   38,   17,   29,   34,   16,
       16,   30,   16,    0,   16,   31,   41,   16,   35,   16,
       36,   21,   16,   16,   37,   16,   16,   39,   16,   16,
        0,   16,    0,   16,    6,   16,   16,   16,   21,   16,
       40,   32,   16,   25,    5,    8,    0,    0,    0,    0,
        0,    0,    0,    0,   16,   16,   28,   24,   20,   27,

        7,    0,    0,    0,    0,    0,    0,    0,    0,   16,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   16,
        0,    0,    0,    0,    0,    0,    0,    1,   16,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    2,    2,
        0,    0,    0,    0,    0,    0,    0,    0,    2,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   58,    0,    0,   58,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    1,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
        1,   22,   16,   16,   23,   24,   24,   24,   24,   25,
       24,   24,   24,   24,   24,   24,   24,   24,   26,   24,
       24,   27,   24,   24,   24,   24,   24,   24,   28,   24,
       29,   29,   29,   29,   30,   29,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   24,   24,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   24,   54,   55,   56,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[57] =
    {   0,
        1,    2,    3,    4,    2,    1,    2,    1,    1,    5,
        6,    2,    2,    7,    8,    2,    1,    9,    2,    1,
        2,    2,   10,   10,   10,   10,   10,   10,    1,    2,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,    2,    2,    2
    } ;

static yyconst short int yy_base[367] =
    {   0,
        0,    0,  542,  543,  543,  543,  520,  534,  532,  530,
        0,  543,  543,  543,   39,  520,  518,  543,  520,  507,
        0,  507,   24,   21,   28,  492,   20,  498,   31,   35,
       44,   19,  484,   39,  498,  490,  543,  472,  543,  504,
      519,  518,  520,  543,  513,  503,  543,  475,   49,   50,
      484,    0,   71,   76,  543,    0,  491,  490,  482,  462,
      481,  482,  465,   59,  461,  490,  466,  466,  473,  462,
       57,  464,  462,   48,  461,  462,   95,  482,  461,  456,
      456,  451,  453,  463,  452,  458,  543,  470,   97,  488,
      543,  543,  543,  543,  543,  543,  543,  543,    0,  472,

      471,   89,   93,  465,  468,    0,  467,  466,  438,  464,
       95,  463,  462,    0,  543,  449,  446,  459,  434,  101,
       79,  457,  456,  441,  454,  440,  452,    0,   99,  449,
      543,  427,  417,  448,  418,  419,    0,  445,  421,  440,
      433,  543,  543,  543,  430,  543,  543,  543,  543,  411,
      454,  543,  411,  417,  412,  543,  543,  416,  543,  418,
      543,  448,  403,  431,  543,  430,  413,  543,  428,  427,
      412,  414,  111,  395,  543,  408,  422,  421,  435,  419,
      543,  543,  418,  543,  543,  543,  400,  392,  396,  390,
      392,  389,  387,  381,  424,  378,  543,  543,  543,  543,

      543,  383,  394,  375,  380,  374,  379,  374,  415,  385,
      377,  370,  383,  383,  383,  375,  381,  407,  114,  374,
      378,  377,  354,  345,  352,  358,  340,  543,  382,  353,
      351,  345,  348,  373,  334,  369,  342,  335,  366,  359,
      328,  117,  118,  357,  119,  120,  122,  339,  338,    0,
      130,  312,  312,  306,  308,  305,  301,  295,    0,  299,
      310,  291,  294,  288,  293,  288,  293,  278,  282,  268,
      253,  234,  237,  236,  234,  223,  213,  221,  229,  211,
      224,  222,  218,  222,  247,  210,  218,  211,  241,  210,
      124,  126,  142,  127,  151,  200,  204,  198,  200,  197,

      195,  189,  193,  204,  185,  190,  184,  189,  184,  189,
      182,  195,  195,  195,  187,  193,  192,  191,  180,  171,
      179,  187,  159,  156,  153,  145,  149,  169,  131,  118,
      103,  133,   46,  131,  157,  145,  161,  153,  190,  193,
      198,  201,  206,  209,  212,  543,  543,  268,  270,  280,
      282,  291,  301,  311,  321,  328,  335,  342,  349,  356,
      358,  365,  372,  379,  386,  396
    } ;

static yyconst short int yy_def[367] =
    {   0,
      347,    1,  347,  347,  347,  347,  347,  348,  347,  347,
      349,  347,  347,  347,  347,  347,  350,  347,  347,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  347,  347,  347,  352,
      348,  348,  353,  347,  347,  350,  347,  347,  347,  347,
      347,  354,  347,  350,  347,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  347,  352,  352,  353,
      347,  347,  347,  347,  347,  347,  347,  347,  354,  347,

      347,  347,  350,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  347,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  347,  347,
      347,  351,  351,  351,  351,  351,  351,  351,  351,  352,
      351,  347,  347,  347,  351,  347,  347,  347,  347,  351,
      351,  347,  351,  347,  351,  347,  347,  351,  347,  351,
      347,  347,  351,  351,  347,  351,  351,  347,  351,  351,
      347,  351,  347,  351,  347,  351,  351,  351,  347,  351,
      347,  347,  351,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  351,  351,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  355,  351,
      347,  347,  347,  347,  347,  347,  347,  355,  355,  351,
      347,  347,  347,  347,  347,  347,  347,  347,  351,  347,
      347,  347,  347,  347,  347,  356,  347,  347,  357,  358,
      347,  359,  360,  358,  347,  347,  359,  347,  347,  361,
      347,  347,  347,  347,  347,  347,  347,  347,  361,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  362,  347,
      363,  347,  347,  363,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  364,  347,  365,  347,  347,  365,  347,  366,  366,
      366,  366,  366,  366,  347,  347,    0,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347
    } ;

static yyconst short int yy_nxt[600] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,    4,    4,   14,   15,    4,   16,   17,    4,   18,
       19,    4,   20,   21,   22,   21,   21,   21,   21,   21,
       23,   21,   24,   25,   26,   27,   28,   21,   29,   30,
       31,   21,   32,   33,   21,   21,   34,   35,   21,   21,
       36,   21,   21,   37,   38,   39,   46,   59,   62,   67,
       47,   77,   64,   63,   78,   60,   65,   72,   68,   73,
       61,   70,   71,   48,   74,   49,   80,   81,   50,  328,
       51,   82,   75,   94,   96,  100,   83,   84,  101,  120,
      102,  111,   76,  103,  112,  124,   95,   97,  129,  125,

      126,  140,  129,  100,  121,  113,  101,  102,  154,  147,
      103,  147,  147,  147,  173,  130,  228,  219,   89,  130,
      245,  243,  245,  251,  155,  245,  246,  292,  246,  292,
      292,  246,  248,  251,  335,  249,  332,  293,  328,  293,
      293,  336,  188,  189,  190,  295,  191,  333,  338,  192,
      193,  252,  253,  254,  295,  255,  338,  194,  256,  257,
      335,  252,  253,  254,  335,  255,  258,  336,  256,  257,
      328,  336,  332,  296,  297,  298,  258,  299,  331,  330,
      300,  301,  296,  297,  298,  328,  299,  328,  302,  300,
      301,  341,  342,  341,  344,  345,  344,  302,  339,  341,

      342,  341,  341,  342,  341,  328,  339,  344,  345,  344,
      344,  345,  344,  345,  345,  345,  329,  328,  327,  326,
      325,  324,  323,  322,  321,  320,  319,  318,  317,  316,
      315,  314,  313,  312,  311,  310,  309,  308,  307,  306,
      305,  304,  303,  285,  289,  343,  285,  290,  343,  285,
      289,  288,  287,  343,  285,  285,  343,  285,  286,  285,
      284,  343,  283,  282,  343,  281,  280,  346,   41,   41,
      279,   41,   41,   41,   41,   41,   41,   41,   45,   45,
       53,   53,  278,   53,   53,   53,   53,   53,   53,   53,
       56,   56,   88,   88,   88,   88,   88,   88,  277,   88,

       88,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   99,   99,  276,   99,   99,   99,   99,   99,   99,
       99,  218,  218,  275,  218,  218,  218,  218,  218,  218,
      218,  240,  274,  273,  272,  271,  270,  240,  242,  269,
      268,  267,  266,  265,  242,  244,  264,  263,  262,  261,
      244,  244,  247,  247,  260,  249,  249,  247,  247,  250,
      243,  234,  243,  250,  250,  250,  259,  259,  291,  239,
      234,  241,  236,  234,  291,  294,  239,  238,  294,  237,
      294,  294,  334,  234,  234,  236,  234,  235,  334,  337,
      234,  337,  233,  232,  337,  337,  340,  340,  340,  340,

      340,  340,  340,  340,  340,  340,  231,  230,  229,  228,
      227,  226,  225,  224,  223,  222,  221,  220,  219,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  200,  199,  179,  198,
      197,  196,  195,  187,  186,  185,  184,  183,  182,  181,
      180,  179,  178,  177,  176,  175,  174,  173,  172,  171,
      170,   89,  169,  168,  167,  166,  165,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  153,  152,  151,  150,
      149,  148,  146,  145,  144,  143,  142,  141,  101,  101,
       91,   89,  139,  138,  137,  136,  135,  134,  133,  132,

      131,  128,  127,  123,  122,  119,  118,  117,  116,  115,
      114,  110,  109,  108,  107,  106,  105,  104,   98,   93,
       54,   92,   91,   42,   42,   89,   87,   86,   85,   79,
       69,   66,   58,   57,   55,   54,   52,   44,   43,   42,
       40,  347,    3,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347

    } ;

static yyconst short int yy_chk[600] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   15,   23,   24,   27,
       15,   32,   25,   24,   32,   23,   25,   30,   27,   30,
       23,   29,   29,   15,   31,   15,   34,   34,   15,  333,
       15,   34,   31,   49,   50,   53,   34,   34,   53,   71,
       54,   64,   31,   54,   64,   74,   49,   50,   77,   74,

       74,   89,  129,  102,   71,   64,  102,  103,  121,  111,
      103,  111,  120,  120,  173,   77,  219,  219,   89,  129,
      242,  243,  245,  246,  121,  247,  242,  291,  245,  292,
      294,  247,  243,  251,  334,  243,  332,  291,  331,  292,
      294,  334,  173,  173,  173,  293,  173,  330,  336,  173,
      173,  246,  246,  246,  295,  246,  338,  173,  246,  246,
      335,  251,  251,  251,  337,  251,  246,  335,  251,  251,
      329,  337,  328,  293,  293,  293,  251,  293,  327,  326,
      293,  293,  295,  295,  295,  325,  295,  324,  293,  295,
      295,  339,  339,  339,  340,  340,  340,  295,  336,  341,

      341,  341,  342,  342,  342,  323,  338,  343,  343,  343,
      344,  344,  344,  345,  345,  345,  322,  321,  320,  319,
      318,  317,  316,  315,  314,  313,  312,  311,  310,  309,
      308,  307,  306,  305,  304,  303,  302,  301,  300,  299,
      298,  297,  296,  290,  289,  339,  288,  287,  340,  286,
      285,  284,  283,  341,  282,  281,  342,  280,  279,  278,
      277,  343,  276,  275,  344,  274,  273,  345,  348,  348,
      272,  348,  348,  348,  348,  348,  348,  348,  349,  349,
      350,  350,  271,  350,  350,  350,  350,  350,  350,  350,
      351,  351,  352,  352,  352,  352,  352,  352,  270,  352,

      352,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  354,  354,  269,  354,  354,  354,  354,  354,  354,
      354,  355,  355,  268,  355,  355,  355,  355,  355,  355,
      355,  356,  267,  266,  265,  264,  263,  356,  357,  262,
      261,  260,  258,  257,  357,  358,  256,  255,  254,  253,
      358,  358,  359,  359,  252,  249,  248,  359,  359,  360,
      244,  241,  240,  360,  360,  360,  361,  361,  362,  239,
      238,  237,  236,  235,  362,  363,  234,  233,  363,  232,
      363,  363,  364,  231,  230,  229,  227,  226,  364,  365,
      225,  365,  224,  223,  365,  365,  366,  366,  366,  366,

      366,  366,  366,  366,  366,  366,  222,  221,  220,  218,
      217,  216,  215,  214,  213,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  196,  195,  194,  193,
      192,  191,  190,  189,  188,  187,  183,  180,  179,  178,
      177,  176,  174,  172,  171,  170,  169,  167,  166,  164,
      163,  162,  160,  158,  155,  154,  153,  151,  150,  145,
      141,  140,  139,  138,  136,  135,  134,  133,  132,  130,
      127,  126,  125,  124,  123,  122,  119,  118,  117,  116,
      113,  112,  110,  109,  108,  107,  105,  104,  101,  100,
       90,   88,   86,   85,   84,   83,   82,   81,   80,   79,

       78,   76,   75,   73,   72,   70,   69,   68,   67,   66,
       65,   63,   62,   61,   60,   59,   58,   57,   51,   48,
       46,   45,   43,   42,   41,   40,   38,   36,   35,   33,
       28,   26,   22,   20,   19,   17,   16,   10,    9,    8,
        7,    3,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1907069.l"
#define INITIAL 0
#line 2 "1907069.l"
    #include<stdio.h>
	#include<stdlib.h>
	#include<string.h>
	#include "1907069.tab.h"
	
#line 619 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 22 "1907069.l"


#line 773 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 348 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 543 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 24 "1907069.l"
{printf("header declaration\n"); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 25 "1907069.l"
{printf("define section\n");}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 29 "1907069.l"
{printf("single line comment\n");}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 30 "1907069.l"
{printf("multiple_line_comment\n");}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 33 "1907069.l"
{                                      return ARRAY ;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 34 "1907069.l"
{                                      return TYPE_INT ;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 35 "1907069.l"
{                                      return TYPE_FLOAT ;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 36 "1907069.l"
{                                      return TYPE_CHAR ;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 42 "1907069.l"
{ yylval.str          = strdup(yytext); return PLUS;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 43 "1907069.l"
{yylval.str          = strdup(yytext); return MINUS;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 44 "1907069.l"
{yylval.str          = strdup(yytext); return MUL;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 45 "1907069.l"
{yylval.str          = strdup(yytext); return DIV;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 54 "1907069.l"
{ yylval.integerValue = atoi(yytext);   return INT ;}  
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 55 "1907069.l"
{yylval.floatValue   = atof(yytext);   return FLOAT ;} 
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 56 "1907069.l"
{yylval.str          = strdup(yytext); return CHAR ;} 
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 57 "1907069.l"
{  yylval.str          = strdup(yytext); return VARIABLE ;} 
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 62 "1907069.l"
{yylval.str          = strdup(yytext); return INCREMENT_DECREMENT ;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 65 "1907069.l"
{ yylval.str          = strdup(yytext);return STRING;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 66 "1907069.l"
{return EQUAL;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 69 "1907069.l"
{ return PRINT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 70 "1907069.l"
{ return PRINT;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 73 "1907069.l"
{  return IF;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 74 "1907069.l"
{   return ELSE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 75 "1907069.l"
{   return ELSEIF;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 79 "1907069.l"
{return WHILE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 80 "1907069.l"
{ return LOOP;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 81 "1907069.l"
{return STORE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 82 "1907069.l"
{return SWITCH;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 83 "1907069.l"
{return DEF;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 86 "1907069.l"
{return GCD;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 87 "1907069.l"
{return LCM;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 88 "1907069.l"
{return SORT;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 89 "1907069.l"
{return ASC;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 90 "1907069.l"
{return DES;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 91 "1907069.l"
{return MAX;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 92 "1907069.l"
{return MIN;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 93 "1907069.l"
{return SIN;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 94 "1907069.l"
{return COS;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 95 "1907069.l"
{return TAN;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 98 "1907069.l"
{return SHOW;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 99 "1907069.l"
{return LENGTH;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 100 "1907069.l"
{ return NEWLINE;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 106 "1907069.l"
{   return BLOCKSTART;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 108 "1907069.l"
{return TO;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 110 "1907069.l"
{   return BLOCKEND;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 117 "1907069.l"
{return LEFTPARANTHESIS;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 118 "1907069.l"
{return RIGHTPARANTHESIS;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 119 "1907069.l"
{return AND;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 120 "1907069.l"
{return OR;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 125 "1907069.l"
{return GREATERTHAN;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 126 "1907069.l"
{return LESSTHAN;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 127 "1907069.l"
{return LESSEQUAL;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 128 "1907069.l"
{return GREATEREQUAL;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 129 "1907069.l"
{return EQUALEQUAL;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 130 "1907069.l"
{return NOTEQUAL ;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 131 "1907069.l"
{ return COMMA;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 132 "1907069.l"
{return SEMICOLON;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 135 "1907069.l"
{
    printf("Function declaration Statement");
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 140 "1907069.l"

	YY_BREAK
case 60:
YY_RULE_SETUP
#line 141 "1907069.l"

	YY_BREAK
case 61:
YY_RULE_SETUP
#line 143 "1907069.l"
{
	printf("Error occour %s\n",yytext);
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 147 "1907069.l"
ECHO;
	YY_BREAK
#line 1170 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 348 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 348 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 347);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 147 "1907069.l"






